import {
  AgentProfile,
  ApprovalRequest,
  IncidentRecord,
  IntegrationConfig,
  MarketplaceListing,
  OwnerProfile,
  SystemLogEntry,
  SystemOverview,
  TaskItem,
  WatchdogMetric,
  WhopPaymentRecord,
} from '../types.js';

export const DEFAULT_OWNER: OwnerProfile = {
  email: 'sadeksanae50@gmail.com',
  role: 'Owner & Super Admin',
  name: 'صادق سناء (Sadek Sanae)',
  mfaEnabled: true,
  lastLogin: new Date().toISOString(),
  sessionIp: '127.0.0.1 (مصادق عليه)',
  activeEnvironment: 'production',
};

export const DEFAULT_AGENTS: AgentProfile[] = [
  {
    id: 'manager',
    name: 'مدير عمليات فايريون الرئيسي (Vireon Core Manager)',
    title: 'المنسق التنفيذي وقائد عمليات الذكاء الاصطناعي',
    department: 'القيادة المركزية',
    avatarColor: 'emerald',
    iconName: 'Cpu',
    roleDescription: 'العقل المدبر المركزي الذي يستقبل أوامر المالك، ويخطط لسير عمل الفرق عبر 9 مراحل، ويوزع المهام، ويتابع الجودة ويرفع التقارير المباشرة للمالك.',
    status: 'active',
    completedTasksCount: 42,
    activeSince: new Date(Date.now() - 30 * 86400000).toISOString(),
    confidenceScore: 99.2,
    capabilities: [
      'تخطيط المهام وتفكيك الأهداف',
      'تفويض وتنسيق الفرق المتعددة',
      'مزامنة حالات سير العمل',
      'حراسة الجودة والأمان',
      'صياغة التقارير التنفيذية للمالك',
    ],
    lastLog: 'جاهز لاستقبال توجيهات المالك. تم مزامنة 12 عميلاً متخصصاً.',
    lastActiveTimestamp: new Date().toISOString(),
  },
  {
    id: 'engineer',
    name: 'مهندس البنية والأنظمة (Systems Architect)',
    title: 'مهندس أول الأنظمة والبنى التحتية',
    department: 'البنية التحتية والأنظمة',
    avatarColor: 'blue',
    iconName: 'Server',
    roleDescription: 'يصمم بنيات الأنظمة المرنة، ومخططات قواعد البيانات، وعقود الـ APIs، وتكاملات الخدمات المصغرة، ويشخص الاختناقات التقنية المعقدة.',
    status: 'active',
    completedTasksCount: 28,
    activeSince: new Date(Date.now() - 30 * 86400000).toISOString(),
    confidenceScore: 98.7,
    capabilities: [
      'تصميم بنية الأنظمة المرنة',
      'تحسين مخططات قواعد البيانات',
      'تحديد مواصفات عقود الـ APIs',
      'تحليل زمن الاستجابة والاختناق',
      'تشخيص الأعطال التقنية الجذرية',
    ],
    lastLog: 'تم التحقق من تكرار قاعدة البيانات مع استجابة أقل من 15 مللي ثانية.',
    lastActiveTimestamp: new Date().toISOString(),
  },
  {
    id: 'developer',
    name: 'المطور البرمجي الرئيسي (Lead Developer)',
    title: 'مهندس برمجيات أول Full-Stack',
    department: 'الهندسة البرمجية',
    avatarColor: 'indigo',
    iconName: 'Code',
    roleDescription: 'يترجم المتطلبات إلى كود نظيف وتراكيبي، ويعالج الثغرات، ويبني التكاملات، وينشئ طلبات السحب والفروقات البرمجية المعتمدة.',
    status: 'active',
    completedTasksCount: 35,
    activeSince: new Date(Date.now() - 30 * 86400000).toISOString(),
    confidenceScore: 98.1,
    capabilities: [
      'تطوير برمجيات Full-Stack كاملة',
      'معالجة الثغرات البرمجية والترقيع',
      'توليد الفروقات البرمجية والـ Diffs',
      'بناء نقاط نهاية الـ API والـ Webhooks',
      'فحوصات واختبارات التكامل والوحدة',
    ],
    lastLog: 'اجتاز فحص معالج الـ Webhook مع مصادقة HMAC بنجاح.',
    lastActiveTimestamp: new Date().toISOString(),
  },
  {
    id: 'frontend',
    name: 'مهندس ومصمم الواجهات الفاخرة (AI Frontend Designer & UX Architect)',
    title: 'كبير مهندسي أنظمة التصميم وتجربة المستخدم الفاخرة',
    department: 'هندسة الواجهات وتجربة المستخدم',
    avatarColor: 'fuchsia',
    iconName: 'Palette',
    roleDescription: 'متخصص مستقل في هندسة واجهات Vireon الفاخرة، ومصفوفة الرموز (Design Tokens)، ودعم اللغة العربية RTL بخط Cairo وPlus Jakarta، والتحسين التفاعلي والحركي (Micro-interactions)، وتعديل ملفات الواجهة مع اختبارات المعاينة Visual Regression.',
    status: 'active',
    completedTasksCount: 27,
    activeSince: new Date(Date.now() - 30 * 86400000).toISOString(),
    confidenceScore: 99.4,
    capabilities: [
      'هندسة أنظمة التصميم ومصفوفات الرموز الفاخرة',
      'صياغة واجهات RTL عربية عالية الدقة والتجاوب',
      'حركات تفاعلية فائقة السلاسة Micro-interactions',
      'المعاينة الحية وتحديث المكونات السريع Hot-Reload',
      'التدقيق البصري وتوافق التباين (WCAG AA 100%)',
      'تعديل ملفات الواجهة الأمامية الحقيقية بدقة جراحية',
    ],
    lastLog: 'اكتمل تدقيق نظام التصميم الزمردي: 100% توافق مع معايير التباين ودعم RTL متقن.',
    lastActiveTimestamp: new Date().toISOString(),
  },
  {
    id: 'qa',
    name: 'حارس الجودة الآلي (QA Sentinel)',
    title: 'مهندس معماري لاختبارات وضمان الجودة الآلية',
    department: 'ضمان الجودة',
    avatarColor: 'teal',
    iconName: 'CheckCircle2',
    roleDescription: 'يشغّل مجموعات الاختبارات الآلية، ويتحقق من سلامة بيئة Staging، ويكتب اختبارات الانحدار، ويضمن عدم وصول أي خلل للإنتاج.',
    status: 'active',
    completedTasksCount: 31,
    activeSince: new Date(Date.now() - 30 * 86400000).toISOString(),
    confidenceScore: 99.0,
    capabilities: [
      'تنفيذ مجموعات الاختبارات المؤتمتة',
      'التحقق من الجودة قبل نشر الإنتاج',
      'فحص الحالات الحدية وحقن الأخطاء',
      'اختبارات قياس الأداء والضغط',
      'منع الانحدار البرمجي (Regression)',
    ],
    lastLog: 'اجتازت حزمة الاختبارات الآلية (48 تأكيداً) بنسبة نجاح 100% وبدون أخطاء.',
    lastActiveTimestamp: new Date().toISOString(),
  },
  {
    id: 'security',
    name: 'درع الأمان السيبراني (Security Shield)',
    title: 'كبير مهندسي الأمان السيبراني وانعدام الثقة (Zero-Trust)',
    department: 'الأمان والامتثال',
    avatarColor: 'rose',
    iconName: 'ShieldAlert',
    roleDescription: 'يفرض بنية انعدام الثقة، ويدقق الكود لثغرات OWASP، ويتحقق من صلاحيات التوكنات، ويعزل المفاتيح السرية من جانب الخادم.',
    status: 'active',
    completedTasksCount: 29,
    activeSince: new Date(Date.now() - 30 * 86400000).toISOString(),
    confidenceScore: 99.8,
    capabilities: [
      'فرض بنية انعدام الثقة (Zero-Trust)',
      'فحص تسرب الرموز والمفاتيح السرية',
      'تدقيق ثغرات OWASP Top 10',
      'فحص حدود الأذونات وصلاحيات RBAC',
      'المصادقة المشفرة لتوقيعات HMAC',
    ],
    lastLog: 'تدقيق انعدام الثقة: 0 أسرار مسربة، جميع المفاتيح معزولة في الخادم.',
    lastActiveTimestamp: new Date().toISOString(),
  },
  {
    id: 'auditor',
    name: 'مدقق ومراقب الأنظمة 24/7 (Watchdog Auditor)',
    title: 'مدقق استمرارية الخدمات ونقاط النهاية في الوقت الفعلي',
    department: 'المراقبة والتدقيق المستمر',
    avatarColor: 'amber',
    iconName: 'Activity',
    roleDescription: 'يراقب السجلات، ويفحص الخدمات المصغرة على مدار الساعة، ويتحقق من تكامل قاعدة البيانات ومعدلات الاستجابة، وينبه الفريق لأي شذوذ.',
    status: 'active',
    completedTasksCount: 54,
    activeSince: new Date(Date.now() - 30 * 86400000).toISOString(),
    confidenceScore: 99.5,
    capabilities: [
      'فحص صحة نقاط النهاية 24/7',
      'كشف الشذوذ والإنذار المبكر',
      'تتبع تسليم Webhooks المدفوعات',
      'التحقق من صلاحية شهادات SSL و DNS',
      'تجميع ومزامنة سجلات التدقيق',
    ],
    lastLog: 'تم فحص جميع الخدمات الـ 6: تعمل بنسبة 100%، متوسط الاستجابة 35 مللي ثانية.',
    lastActiveTimestamp: new Date().toISOString(),
  },
  {
    id: 'devops',
    name: 'مهندس السحابة والعمليات (DevOps & Cloud Master)',
    title: 'مهندس موثوقية المواقع والبنية السحابية (SRE)',
    department: 'البنية التحتية والعمليات السحابية',
    avatarColor: 'sky',
    iconName: 'Cloud',
    roleDescription: 'يدير مسارات النشر الآلي CI/CD، ويعزل بيئات الإنتاج والتطوير، ويهيئ الاسترجاع الفوري (Rollback)، ويضمن استمرارية الخدمة بدون انقطاع.',
    status: 'active',
    completedTasksCount: 26,
    activeSince: new Date(Date.now() - 30 * 86400000).toISOString(),
    confidenceScore: 98.9,
    capabilities: [
      'عزل بيئات الإنتاج والتطوير (Staging vs Prod)',
      'الاسترجاع التلقائي الفوري (Rollback)',
      'إدارة النشر التجريبي Canary Deployment',
      'التحجيم التلقائي للحاويات والموارد',
      'مراقبة استقرار خوادم Cloud Run',
    ],
    lastLog: 'بيئة الإنتاج مستقرة وصحية. حاوية Cloud Run تعمل بكفاءة.',
    lastActiveTimestamp: new Date().toISOString(),
  },
  {
    id: 'payments',
    name: 'حارس مدفوعات Whop (Payment Guardian)',
    title: 'أخصائي التكنولوجيا المالية وتكاملات Whop',
    department: 'المالية والمدفوعات',
    avatarColor: 'emerald',
    iconName: 'CreditCard',
    roleDescription: 'يضمن تكاملاً مثالياً مع منصة Whop، ويتحقق من توقيعات الـ Webhook المشفرة بواسطة HMAC-SHA256، ويراقب تسوية المعاملات المالية.',
    status: 'active',
    completedTasksCount: 22,
    activeSince: new Date(Date.now() - 30 * 86400000).toISOString(),
    confidenceScore: 99.4,
    capabilities: [
      'استقبال Whop Webhook والتحقق بـ HMAC',
      'تدقيق دفتر المعاملات والتسويات المالية',
      'إدارة دورة حياة الاشتراكات والتراخيص',
      'استرداد المدفوعات المتعثرة والنزاعات',
      'كشف ومنع تسرب الإيرادات',
    ],
    lastLog: 'تم فحص الـ Webhook من Whop: نسبة تطابق التوقيعات 100%.',
    lastActiveTimestamp: new Date().toISOString(),
  },
  {
    id: 'marketplace',
    name: 'منسق ومراقب المتجر الرقمي (Marketplace Curator)',
    title: 'مدير كتالوج وعمليات المتجر الرقمي',
    department: 'عمليات المتجر الرقمي',
    avatarColor: 'purple',
    iconName: 'ShoppingBag',
    roleDescription: 'يراجع المنتجات الرقمية، ويتحقق من خدمات البائعين ونقاط التسليم الآلي، ويتأكد من مطابقة المنتجات لمعايير الجودة والأمان.',
    status: 'active',
    completedTasksCount: 19,
    activeSince: new Date(Date.now() - 30 * 86400000).toISOString(),
    confidenceScore: 98.2,
    capabilities: [
      'تدقيق جودة منتجات المتجر',
      'فحص سلامة تسليم الملفات والأصول الرقمية',
      'تقييم موثوقية البائعين',
      'تصنيف وفهرسة المنتجات للبحث',
      'منع الاحتيال والقرصنة الرقمية',
    ],
    lastLog: 'اكتمل تدقيق الكتالوج: 3 منتجات نشطة مؤكدة وجاهزة للبيع.',
    lastActiveTimestamp: new Date().toISOString(),
  },
  {
    id: 'support',
    name: 'محامي وخدمة العملاء الآلي (Customer Advocate)',
    title: 'قائد نجاح العملاء والتصعيد الذكي',
    department: 'نجاح ودعم العملاء',
    avatarColor: 'pink',
    iconName: 'Headphones',
    roleDescription: 'يتعامل مع استفسارات العملاء بناءً على البيانات المصادق عليها، ويحل المشكلات الشائعة، ويصعد الحالات الحساسة والمالية فوراً للمالك.',
    status: 'active',
    completedTasksCount: 38,
    activeSince: new Date(Date.now() - 30 * 86400000).toISOString(),
    confidenceScore: 97.9,
    capabilities: [
      'معالجة وحل استفسارات العملاء',
      'الاستعلام عن البيانات المعتمدة',
      'تهدئة وحل النزاعات البرمجية',
      'بروتوكول التصعيد الفوري للمالك',
      'أتمتة الأسئلة الشائعة وقاعدة المعرفة',
    ],
    lastLog: 'قائمة انتظار الدعم 0 استفسارات معلقة. محفزات التصعيد نشطة.',
    lastActiveTimestamp: new Date().toISOString(),
  },
  {
    id: 'seo',
    name: 'مطور النمو والظهور (Growth & SEO Optimizer)',
    title: 'خبير تحسين محركات البحث واستراتيجيات الظهور',
    department: 'النمو والظهور الرقمي',
    avatarColor: 'yellow',
    iconName: 'TrendingUp',
    roleDescription: 'يحلل باستمرار أداء فايريون في نتائج البحث، والبيانات الوصفية OpenGraph، ومخططات JSON-LD المنظمة، وفرص الكلمات المفتاحية.',
    status: 'active',
    completedTasksCount: 17,
    activeSince: new Date(Date.now() - 30 * 86400000).toISOString(),
    confidenceScore: 98.0,
    capabilities: [
      'تدقيق خرائط الموقع وفهرسة الصفحات',
      'التحقق من بيانات JSON-LD Schema المنظمة',
      'استراتيجية الكلمات المفتاحية والمحتوى',
      'تحسين مؤشرات أداء الويب الأساسية (Core Web Vitals)',
      'توصيات تصدر نتائج البحث SERP',
    ],
    lastLog: 'فحص البيانات الوصفية: علامات OpenGraph ومخطط JSON-LD سليم ومطابق.',
    lastActiveTimestamp: new Date().toISOString(),
  },
  {
    id: 'analytics',
    name: 'محلل ذكاء الأعمال والبيانات (Business Intelligence)',
    title: 'كبير محللي البيانات والتحليلات الكمية',
    department: 'البيانات والتحليلات المتقدمة',
    avatarColor: 'violet',
    iconName: 'BarChart3',
    roleDescription: 'يحلل حركة الزوار، ومسارات التحويل (Funnels)، وحجم التداول الإجمالي في المتجر، ويقدم رؤى قابلة للتنفيذ المباشر.',
    status: 'active',
    completedTasksCount: 24,
    activeSince: new Date(Date.now() - 30 * 86400000).toISOString(),
    confidenceScore: 98.6,
    capabilities: [
      'تحسين مسارات الشراء ومعدلات التحويل',
      'تحليلات الاحتفاظ بالعملاء وسلوك المجموعات',
      'نمذجة الإيرادات والنمو المالي',
      'تتبع مصادر الزيارات والحملات',
      'التنبؤ المبكر بنسب الإلغاء (Churn)',
    ],
    lastLog: 'تحليل التحويل اليومي: معدل إتمام عمليات الشراء 94.2%.',
    lastActiveTimestamp: new Date().toISOString(),
  },
  {
    id: 'operations',
    name: 'قائد العمليات اليومية (Operations Lead)',
    title: 'مدير العمليات اليومية وسير الإجراءات',
    department: 'إدارة العمليات',
    avatarColor: 'slate',
    iconName: 'Briefcase',
    roleDescription: 'ينفذ إجراءات التشغيل القياسية، وينسق الملخصات اليومية، ويشرف على النسخ الاحتياطية الآلية، ويتابع مؤشرات الأداء التشغيلية.',
    status: 'active',
    completedTasksCount: 45,
    activeSince: new Date(Date.now() - 30 * 86400000).toISOString(),
    confidenceScore: 99.1,
    capabilities: [
      'ملخصات وتقارير الحالة التشغيلية اليومية',
      'تنفيذ أدلة التشغيل الآلية (Runbooks)',
      'توثيق ما بعد الحوادث وتحليل الأسباب',
      'تخصيص الموارد والحصص السحابية',
      'تنسيق المزامنة بين مختلف الفرق',
    ],
    lastLog: 'اكتملت المزامنة التشغيلية. جميع أدلة التشغيل جاهزة للعمل 24/7.',
    lastActiveTimestamp: new Date().toISOString(),
  },
];

export const DEFAULT_WATCHDOG_METRICS: WatchdogMetric[] = [
  {
    id: 'metric-1',
    service: 'بوابة API فايريون الرئيسية (Core Gateway)',
    endpoint: '/api/v1/health',
    status: 'operational',
    latencyMs: 38,
    uptime24h: 99.98,
    lastChecked: new Date().toISOString(),
    errorRatePercent: 0.02,
  },
  {
    id: 'metric-2',
    service: 'مسار استقبال Whop Webhooks',
    endpoint: '/api/webhooks/whop',
    status: 'operational',
    latencyMs: 44,
    uptime24h: 100.0,
    lastChecked: new Date().toISOString(),
    errorRatePercent: 0.0,
  },
  {
    id: 'metric-3',
    service: 'خدمة كتالوج المتجر الرقمي',
    endpoint: '/api/marketplace/products',
    status: 'operational',
    latencyMs: 52,
    uptime24h: 99.94,
    lastChecked: new Date().toISOString(),
    errorRatePercent: 0.05,
  },
  {
    id: 'metric-4',
    service: 'عنقود قواعد بيانات PostgreSQL المكرر',
    endpoint: 'db-replica.vireon.internal',
    status: 'operational',
    latencyMs: 14,
    uptime24h: 99.99,
    lastChecked: new Date().toISOString(),
    errorRatePercent: 0.01,
  },
  {
    id: 'metric-5',
    service: 'حماية Edge SSL وجدار Cloudflare WAF',
    endpoint: 'https://vireon.ai',
    status: 'operational',
    latencyMs: 22,
    uptime24h: 100.0,
    lastChecked: new Date().toISOString(),
    errorRatePercent: 0.0,
  },
  {
    id: 'metric-6',
    service: 'طابور تصعيد دعم العملاء',
    endpoint: '/api/support/tickets',
    status: 'operational',
    latencyMs: 41,
    uptime24h: 99.95,
    lastChecked: new Date().toISOString(),
    errorRatePercent: 0.03,
  },
];

export const DEFAULT_TASKS: TaskItem[] = [
  {
    id: 'task-101',
    title: 'التدقيق الأمني الآلي 24/7 للثغرات والرموز السرية',
    description: 'أكمل درع الأمان ومدقق الأنظمة فحصاً شاملاً لنقاط نهاية الـ API، ومفاتيح البيئة وتوقيعات توكنات الصلاحيات.',
    priority: 'high',
    stage: 'report',
    status: 'completed',
    assignedAgent: 'security',
    source: 'scheduled_audit',
    createdBy: 'مدقق الأنظمة 24/7',
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 1.8).toISOString(),
    requiresApproval: false,
    workflowHistory: [
      {
        stage: 'detect',
        agent: 'auditor',
        timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
        output: 'بدء فحص دوري عبر 14 مساراً للخادم و 3 مفاتيح تكامل.',
        status: 'pass',
      },
      {
        stage: 'diagnose',
        agent: 'security',
        timestamp: new Date(Date.now() - 3600000 * 1.9).toISOString(),
        output: 'جميع التوكنات معزولة ومقنعة في الخادم. صفر تسريبات في حزم المتصفح.',
        status: 'pass',
      },
      {
        stage: 'report',
        agent: 'manager',
        timestamp: new Date(Date.now() - 3600000 * 1.8).toISOString(),
        output: 'تم تأكيد سلامة الأمان بالكامل. صفر ثغرات أمنية.',
        status: 'pass',
      },
    ],
    artifacts: [
      {
        id: 'art-1',
        title: 'سجل تدقيق الأمان وانعدام الثقة (Zero-Trust Security Log)',
        type: 'security_audit',
        content: `=== تقرير تدقيق الأمان السيبراني وانعدام الثقة لفايريون ===
الوقت: ${new Date().toISOString()}
المفتش: درع الأمان السيبراني (Vireon Security Shield)
الهدف: 14 مسار API، بيانات اعتماد قاعدة البيانات، توقيعات Whop HMAC

النتائج:
[نجاح] WHOP_API_KEY: مقنع ومعزول من جانب الخادم فقط.
[نجاح] DATABASE_URL: معزول داخل شبكة VPC خاصة.
[نجاح] حماية حقن OWASP: استخدام استعلامات محصنة بالمعاملات (Parameterized).
[نجاح] بوابة المالك (Owner Gatekeeper): نشطة لأي عملية تدميرية أو حساسة.

الخلاصة: النظام يعمل بأقصى درجات أمان انعدام الثقة (Zero-Trust).`,
        createdAt: new Date(Date.now() - 3600000 * 1.8).toISOString(),
      },
    ],
  },
  {
    id: 'task-102',
    title: 'مطابقة تسويات ومدفوعات Whop عبر الـ Webhook',
    description: 'تحقق مسؤول المدفوعات من صحة أحدث عمليات الشراء وطابق توقيعات التشفير SHA-256 HMAC.',
    priority: 'medium',
    stage: 'report',
    status: 'completed',
    assignedAgent: 'payments',
    source: 'webhook_event',
    createdBy: 'مسؤول مدفوعات Whop',
    createdAt: new Date(Date.now() - 3600000 * 1.2).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 1.1).toISOString(),
    requiresApproval: false,
    workflowHistory: [
      {
        stage: 'detect',
        agent: 'auditor',
        timestamp: new Date(Date.now() - 3600000 * 1.2).toISOString(),
        output: 'تم اكتشاف حمولة Webhook واردة من خوادم Whop.',
        status: 'pass',
      },
      {
        stage: 'verify',
        agent: 'payments',
        timestamp: new Date(Date.now() - 3600000 * 1.15).toISOString(),
        output: 'تمت مطابقة توقيع HMAC ومطابقته مع WHOP_WEBHOOK_SECRET. تأكيد الدفع بنجاح.',
        status: 'pass',
      },
      {
        stage: 'report',
        agent: 'manager',
        timestamp: new Date(Date.now() - 3600000 * 1.1).toISOString(),
        output: 'تم تأكيد التسوية ومزامنة الإيرادات في لوحة التحكم.',
        status: 'pass',
      },
    ],
    artifacts: [],
  },
];

export const DEFAULT_INTEGRATIONS: IntegrationConfig[] = [
  {
    id: 'int-github',
    provider: 'github',
    name: 'مستودع GitHub الحقيقي (Branches & PRs & Commits)',
    status: 'connected',
    maskedKey: 'ghp_prod_••••••••••••••••••••8b92',
    hasKey: true,
    lastPingAt: new Date().toISOString(),
    lastPingStatus: 'success',
    pingLatencyMs: 42,
    requiredFields: ['GITHUB_TOKEN', 'GITHUB_OWNER', 'GITHUB_REPO'],
    docsUrl: 'https://docs.github.com/rest',
    realVerified: true,
  },
  {
    id: 'int-vercel',
    provider: 'vercel',
    name: 'محرك نشر Vercel السحابي (Preview & Prod & Rollback)',
    status: 'connected',
    maskedKey: 'vcl_sec_••••••••••••••••••••9e3f',
    hasKey: true,
    lastPingAt: new Date().toISOString(),
    lastPingStatus: 'success',
    pingLatencyMs: 36,
    requiredFields: ['VERCEL_TOKEN', 'VERCEL_PROJECT_ID'],
    docsUrl: 'https://vercel.com/docs/rest-api',
    realVerified: true,
  },
  {
    id: 'int-whop',
    provider: 'whop',
    name: 'بوابة مدفوعات Whop API وتوقيعات HMAC',
    status: 'connected',
    maskedKey: 'whop_api_prod_••••••••••••••••••••39a1',
    hasKey: true,
    lastPingAt: new Date().toISOString(),
    lastPingStatus: 'success',
    pingLatencyMs: 38,
    requiredFields: ['WHOP_API_KEY', 'WHOP_WEBHOOK_SECRET'],
    docsUrl: 'https://docs.whop.com',
    realVerified: true,
  },
  {
    id: 'int-postgres',
    provider: 'database',
    name: 'قاعدة بيانات PostgreSQL المستقلة والمتزامنة',
    status: 'connected',
    maskedKey: 'postgres://vireon_admin:••••••••@10.128.0.4:5432/vireon_prod',
    hasKey: true,
    lastPingAt: new Date().toISOString(),
    lastPingStatus: 'success',
    pingLatencyMs: 14,
    requiredFields: ['DATABASE_URL'],
    docsUrl: 'https://www.postgresql.org/docs',
    realVerified: true,
  },
  {
    id: 'int-gateway',
    provider: 'vireon_api',
    name: 'بوابة Vireon الأساسية ومسارات الوكلاء الـ 14',
    status: 'connected',
    maskedKey: 'gateway_jwt_sec_••••••••••••••••••••f4e2',
    hasKey: true,
    lastPingAt: new Date().toISOString(),
    lastPingStatus: 'success',
    pingLatencyMs: 18,
    requiredFields: ['VIREON_API_URL'],
    docsUrl: 'https://vireon.ai/docs',
    realVerified: true,
  },
];

export const DEFAULT_PAYMENTS: WhopPaymentRecord[] = [
  {
    id: 'pay-1',
    whopOrderId: 'ord_whop_98124',
    whopEventId: 'evt_pay_00192',
    amount: 149.0,
    currency: 'USD',
    status: 'confirmed',
    customerEmail: 'alex.v@cloudsystems.io',
    productTitle: 'باقة تشغيل فايريون الذاتية 24/7 (اشتراك شهري)',
    productType: 'membership',
    timestamp: new Date(Date.now() - 3600000 * 3).toISOString(),
    verifiedSignature: true,
  },
  {
    id: 'pay-2',
    whopOrderId: 'ord_whop_98125',
    whopEventId: 'evt_pay_00193',
    amount: 399.0,
    currency: 'USD',
    status: 'confirmed',
    customerEmail: 'sarah.m@apexventures.co',
    productTitle: 'عنقود فايريون السحابي المتكامل لـ 13 عميلاً ذكياً',
    productType: 'api_license',
    timestamp: new Date(Date.now() - 3600000 * 8).toISOString(),
    verifiedSignature: true,
  },
  {
    id: 'pay-3',
    whopOrderId: 'ord_whop_98126',
    whopEventId: 'evt_pay_00194',
    amount: 49.0,
    currency: 'USD',
    status: 'confirmed',
    customerEmail: 'dev.marcus@lumina.tech',
    productTitle: 'حزمة المطور الذكي وحارس الجودة الآلي',
    productType: 'digital_download',
    timestamp: new Date(Date.now() - 3600000 * 14).toISOString(),
    verifiedSignature: true,
  },
];

export const DEFAULT_MARKETPLACE: MarketplaceListing[] = [
  {
    id: 'prod-1',
    title: 'باقة تشغيل فايريون الذاتية 24/7 (Vireon Autonomous Operations)',
    category: 'برمجيات سحابية SaaS',
    sellerName: 'Vireon Technologies Inc.',
    sellerId: 'seller_vireon_core',
    price: 149.0,
    status: 'verified_active',
    healthScore: 99,
    qaPassRate: 100,
    salesCount: 84,
    revenue: 12516.0,
    lastScannedAt: new Date().toISOString(),
    securityNotes: 'جميع نقاط النهاية محمية بحدود الطلبات والتوكنات المشفرة.',
  },
  {
    id: 'prod-2',
    title: 'عنقود فايريون السحابي لـ 13 عميلاً ذكياً (Enterprise Cluster)',
    category: 'بنية تحتية للمؤسسات',
    sellerName: 'Vireon Technologies Inc.',
    sellerId: 'seller_vireon_core',
    price: 399.0,
    status: 'verified_active',
    healthScore: 98,
    qaPassRate: 100,
    salesCount: 29,
    revenue: 11571.0,
    lastScannedAt: new Date().toISOString(),
    securityNotes: 'عزل VPC مخصص مع تجاوز تلقائي للفشل في مناطق متعددة.',
  },
  {
    id: 'prod-3',
    title: 'حزمة المطور الذكي وحارس الجودة الآلي (QA & Dev Package)',
    category: 'أدوات المطورين',
    sellerName: 'Vireon Technologies Inc.',
    sellerId: 'seller_vireon_core',
    price: 49.0,
    status: 'verified_active',
    healthScore: 100,
    qaPassRate: 100,
    salesCount: 142,
    revenue: 6958.0,
    lastScannedAt: new Date().toISOString(),
    securityNotes: 'حزم برمجية موقعة رقمياً ومحمية بحواجز فحص الانحدار.',
  },
];

export const DEFAULT_INCIDENTS: IncidentRecord[] = [
  {
    id: 'inc-01',
    title: 'معالجة ارتفاع طفيف في زمن استجابة الـ Webhook',
    severity: 'info',
    component: 'مسار استقبال Whop Webhook',
    status: 'resolved',
    detectedAt: new Date(Date.now() - 3600000 * 22).toISOString(),
    resolvedAt: new Date(Date.now() - 3600000 * 21.8).toISOString(),
    diagnosis: 'ازدحام شبكي عابر على البوابة الطرفية. قام مهندس العمليات DevOps بالتحجيم التلقائي لخيوط المعالجة.',
    impact: 'زيادة عابرة 15ms في الاستجابة، مع صفر Webhooks مفقودة.',
  },
];

export const DEFAULT_APPROVALS: ApprovalRequest[] = [
  {
    id: 'appr-01',
    taskId: 'task-staged-001',
    taskTitle: 'تحسين فهارس قاعدة البيانات المركبة لطلبات المتجر الرقمي',
    actionType: 'destructive_db',
    description: 'تنفيذ إنشاء فهارس متزامنة على جدول marketplace_orders(created_at, status, seller_id) لتسريع استعلامات التقارير بنسبة 45%. معدّة من مهندس الأنظمة.',
    agent: 'engineer',
    riskLevel: 'high',
    status: 'pending',
    createdAt: new Date(Date.now() - 3600000 * 1).toISOString(),
    payload: {
      commandOrQuery: `CREATE INDEX CONCURRENTLY idx_orders_status_created 
ON marketplace_orders (created_at DESC, status) 
WHERE deleted_at IS NULL;`,
      impactAnalysis: 'بدون قفل للجداول (تنفيذ CONCURRENT). يقلل زمن استعلامات التحليلات بنسبة 45%.',
      rollbackPlan: `DROP INDEX CONCURRENTLY IF EXISTS idx_orders_status_created;`,
      environment: 'production',
    },
  },
];

export const DEFAULT_LOGS: SystemLogEntry[] = [
  {
    id: 'log-1',
    timestamp: new Date().toISOString(),
    agentId: 'manager',
    level: 'info',
    module: 'القيادة المركزية',
    message: 'مركز قيادة فايريون للذكاء الاصطناعي نشط. 13 عميلاً متخصصاً متزامناً.',
  },
  {
    id: 'log-2',
    timestamp: new Date(Date.now() - 60000).toISOString(),
    agentId: 'auditor',
    level: 'success',
    module: 'رادار المراقبة',
    message: 'اكتملت جولة فحص الصحة العامة: 6/6 خدمات مصغرة تعمل بكفاءة (متوسط 35 مللي ثانية).',
  },
  {
    id: 'log-3',
    timestamp: new Date(Date.now() - 120000).toISOString(),
    agentId: 'security',
    level: 'security',
    module: 'درع الأمان',
    message: 'اكتمل تدقيق انعدام الثقة: صفر تسريبات، تم تأكيد صلاحيات المسؤول الأعلى لـ sadeksanae50@gmail.com.',
  },
  {
    id: 'log-4',
    timestamp: new Date(Date.now() - 180000).toISOString(),
    agentId: 'payments',
    level: 'info',
    module: 'سجل Whop',
    message: 'مسار Whop Webhook يستمع مع تفعيل التحقق التشفيري SHA-256 HMAC.',
  },
];

export const DEFAULT_OVERVIEW: SystemOverview = {
  healthScore: 99.8,
  activeAgentsCount: 14,
  openIncidentsCount: 0,
  pendingApprovalsCount: 1,
  totalRevenue24h: 597.0,
  ordersCount24h: 3,
  webhookSuccessRate: 100.0,
  averageLatencyMs: 32.4,
  gitCommit: 'a8f9c2d (main)',
  activeEnvironment: 'production',
  lastWatchdogSweep: new Date().toISOString(),
  runningWorkersCount: 6,
  activeJobsCount: 6,
};
